### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Mefist0** [tngraf/OBD.Net#1]
Hello, Thomas!

My name is Anatoly. I'm from Russia. I work with Volkswagen cars.
Some time ago I tried to write a diagnostic program. I did it, but I did just connection via K-line and in my program I wrote wake-up (FastInit) method and StartCommunication (0x81 service). It works.
But I don't have enough experience to write the program on.

Can I help you with OBD.Net project? For example, I can test the program with different ECU's.
I know C#.NET and German :)

Thank you in advance!

**Comment by tngraf** [comment]
Hello Anatoly,
I did this Project just for fun. Once I read an article in a Magazine about ODB communication it I wanted to find out what Kind of Information I can extract from my car. I have no technical Background on cars or OBD ... but I'm a professional Software developer.
You can use the code for whatever you want. If you do relevant changes to the code I would appreciate a pull request.

Best regards,
Thomas
